[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tpdb"
version = "0.1.0"
requires-python = ">=3.8"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "textual",
]